const teamData = [
  {id: '1',
   name: 'The A-Team',
   members: [
    {id: 1,
     name: 'Matt Taylor',
     email: 'matt@mtaylor.tech',
     role: 'Front-End Developer'},
    {id: 2,
     name: 'John "Hannibal" Smith',
     email: 'hannibal@mtaylor.tech',
     role: 'Master of Disguise'},
    {id: 3,
     name: 'Templeton "Faceman" Peck',
     email: 'faceman@mtaylor.tech',
     role: 'Master of Persuasion'},
    {id: 4,
     name: 'Bosco "B.A." Baracus',
     email: 'b.a.baracus@mtaylor.tech',
     role: 'Muscle'},
    {id: 5,
     name: 'H.M. "Howling Mad" Murdock',
     email: 'murdock@mtaylor.tech',
     role: 'Pilot'}]},
   {id: '2',
    name: 'TKO',
    members: [
     {id: 1,
      name: 'Matt Taylor',
      email: 'matt@mtaylor.tech',
      role: 'Front-End Developer'},
     {id: 2,
      name: 'Jason Morningstar',
      email: 'jason@mtaylor.tech',
      role: 'Master Storyteller'},
     {id: 3,
      name: 'Kate Hill',
      email: 'kate@mtaylor.tech',
      role: 'Master of Lore'}]},
];

export default teamData;
